### ISSUE TITLE
Oracle Errors

### ISSUE THREAD

**Issue by kog4096** [mattn/go-oci8#260]
I'm trying to get the actual Oracle error (code/text) back from a failed connection, but that doesn't seem to be happening. Can this be done? Here is my sample code:
`	db, err := sql.Open("oci8", connectStr)
	if err != nil {
		return nil, err
	}

	err = db.Ping()
	if err != nil {
		db.Close()
		return nil, err
	}
`
In the case of a bad user/password, db.Ping() throws an error of "ping failed", but the actual reason is unknown unless I connect to the database with another client. Is this something that I'm doing incorrectly?

**Comment by MichaelS11** [comment]
You are not doing anything wrong.

How the Go SQL driver works is a little weird. It should return driver: bad connection. Have seen other drivers not return that but that is not what the Go SQL driver notes say to do. Have seen the solution in other driver to return additional error information with log, which probably something that should be done but is not implemented right now.

Go SQL driver notes:
https://golang.org/pkg/database/sql/driver/#Pinger

> If Conn.Ping returns ErrBadConn, DB.Ping and DB.PingContext will remove the Conn from pool.

**Comment by MichaelS11** [comment]
Not that I am aware of at this time.

@mattn 

Any thoughts on this? Should I add log? Or have another idea on what you would like to see?

**Comment by mattn** [comment]
AFAICS, `return ociGetError(rv, c.err)` will solve this?

**Comment by MichaelS11** [comment]
If you want to do the log method would be some thing like the following (not real code):

(already checked for error and has error)

err = ociGetError
if isBadConnection(err) {
  log.print(err)
  return driver.ErrBadConn
} else {
  return err
}

**Comment by mattn** [comment]
I think user can check the err via conn.Ping() and what happen.

**Comment by MichaelS11** [comment]
Pretty sure ping needs to return driver.ErrBadConn instead of the ORA error.

https://golang.org/src/database/sql/sql.go?s=21213:21265#L726

**Comment by kog4096** [comment]
If I adjust the ping code to use ociGetError, I do get this (which is slightly more descriptive):
```
Could not connect to database: driver: bad connection
```
That still isn't an idea error for this condition. With RazorSQL I see the real reason for the failure:
```
ORA-01017:
invalid username/password; logon denied
```
I think it's fine for the ping to give a generic failure, but is there a way to get this ORA error?

**Comment by MichaelS11** [comment]
That is what we are working on @kog4096 . Asking @mattn if it is alright to log that information or if there is another way he wants to do it.

**Comment by kog4096** [comment]
Thanks @MichaelS11

**Comment by mattn** [comment]
I am skeptical to output log with Ping. For example, someone use Ping to check database connection repeatedly, the output will be unusable. If we should add this, I want to add ConnectHook that implemented on go-sqlite3 to call native driver function.

**Comment by MichaelS11** [comment]
Up to you.

Here is what I did:
https://github.com/MichaelS11/go-cql-driver/blob/master/connection.go#L18-L77

**Comment by mattn** [comment]
How about to add `_driverlogs=true` in connection string?

**Comment by mattn** [comment]
I prefer that disabled logger in default.

**Comment by MichaelS11** [comment]
PR https://github.com/mattn/go-oci8/pull/261

**Comment by MichaelS11** [comment]
This should now be fixed. Can enable logging with something like:

`OCI8Driver.Logger = log.New(os.Stderr, "oci8 ", log.Ldate|log.Ltime|log.LUTC|log.Llongfile)`

**Comment by kog4096** [comment]
Thanks, I'll check it out.

**Comment by MichaelS11** [comment]
All good? Close this?

**Comment by kog4096** [comment]
Sorry for the late response. I was able to do some testing, but I still don't seem to get the level of detail I was hoping for. I now get "Could not connect to database: driver: bad connection", but when connecting with a client like RazorSQL I get: "ORA-28040: No matching authentication protocol" (or other detailed ORA message). Is there a way to access an error like this?

**Comment by MichaelS11** [comment]
Did you turn on the logging?

Example:
`OCI8Driver.Logger = log.New(os.Stderr, "oci8 ", log.Ldate|log.Ltime|log.LUTC|log.Llongfile)`

**Comment by kog4096** [comment]
Thanks @MichaelS11 - that gets me closer. I now get: 
`Ping error: ORA-01012: not logged on`
from the ping attempt, but the initial connection does not error as I'd expect in this case. The test case has a locked account; with sqlplus I get:
`ORA-28000: the account is locked`
I'll be doing more testing on this.

**Comment by MichaelS11** [comment]
Welcome. Will look into it more later, see if anything can be improved.

**Comment by MichaelS11** [comment]
@kog4096 This should now be fixed for login. Will error on database open instead of ping.

Please retest and close if fixed.
